### ISSUE TITLE
How to use a markers array snippet in frontend code?

### ISSUE THREAD

**Issue by ghost** [bnomei/kirby-styledmap#4]
Thank you very much for creating this excellent plugin. It helps to deal with showing maps. 👍 

I have just one thing that I can't get to work, and that is a markers array.  

I have a collection of pages under a parent page. Each child has a location field and shows a map. On the parent page, I want to show all the locations (markers) on a single map. I, therefore, want to display one map with the optional markers array. How would that look like in for the template? 

You show the array here: [https://github.com/bnomei/kirby-styledmap#page-or-site-method](https://github.com/bnomei/kirby-styledmap#page-or-site-method), but every time I add the snippet name as the last array element it bugs out.

I'm also unaware how to purposefully fill the other elements, especially if I need another redundant location after the title array element when all the elements I want to have on the map are in the markers array? 

Do you maybe have a working code snippet that shows the PHP equivalent to the kirbytext example from the documentation?

Best regards
Mike

**Comment by bnomei** [comment]
hi mike,

you correctly found out that using the site/page method with a style is broken. i will fix this asap, but probably not today. you can [subscribe to issue #5](https://github.com/bnomei/kirby-styledmap/issues/5) to get an email when its done.

i just verified that using the **kirby tag** works. so you might try wrapping the kirby tag in the `kirbytext` php helper and echo that. like this...

``` php
echo kirbytext('(styledmap: Lualualei Beach Park style: sm-example-json markers: sm-example-markers location: 21.437127, -158.186699, 10)');
```

**Comment by bnomei** [comment]
style seems fine now. please make sure you only add names of existing snippets to the array. having a typo in the snippet name could also happen very easily.

```php
echo $page->styledmap(				// or $site->styledmap(
    'Lualualei Beach Park', 		// title
    '21.437127, -158.186699, 15',	// array, url, location or fieldname
    [								// optional: data for center marker
        'info' => 'Uke in Hawaii',
        'icon' => '/assets/plugins/kirby-styledmap/sm-example-icon.svg',
    ],
    // this would be site/snippets/sm-example-style.php or within the plugin
    'sm-example-style', 			// optional: name of style snippet
    // this would be site/snippets/sm-example-markers.php or within the plugin
    'sm-example-markers' 			// optional: name of markers snippet
);
```

your markers snippet could look like the provided example:
https://github.com/bnomei/kirby-styledmap/blob/master/snippets/sm-example-markers.php

unless you are already familiar with `snippets` in kirby consider [reading this](https://getkirby.com/docs/templates/snippets) on how to pass your page object to a snippet to build the markers array.

please try again with current version and report back and/or close this issue. :-)

**Comment by ghost** [comment]
Hello Bruno,

I finally had a chance to work with the map again and it works! Thank you very much for the support.  👍 

❓ There is one more question. Can I get rid of the icon for the "center" marker? In my case, I want it only to position the map so that all the other pins are visible, but there is no real point of interest behind it.

Thank you.

**Comment by bnomei** [comment]
setting the default marker icon to a transparent png (https://github.com/bnomei/kirby-styledmap#custom-marker-icon) to change the center and using a different icon-file(png/svg) within the marker array should do the trick.

**Comment by ghost** [comment]
🤔But that then changes the marker on all the subsequent calls to a transparent image? How do I change it back on, for example, a details page, where I grab the location from a location field? 

`<?= kirbytext('(styledmap: style: sm-example-json location: location)'); ?>`

**Comment by bnomei** [comment]
you could get, change and restore the config param for the center marker icon when rendering the special map. like this...

```php
$currentIcon = c::get('plugin.styledmap.jsmarker.icon'); // save current
c::set('plugin.styledmap.jsmarker.icon', 'PATH_TO_TRANSPARENT_ICON'); // set temp
// method calls to render map with lots of markers but center has none
c::set('plugin.styledmap.jsmarker.icon', $currentIcon); // restore icon for center for next call
```
