### ISSUE TITLE
Use Styledmap multiple times on the same page?

### ISSUE THREAD

**Issue by janstieler** [bnomei/kirby-styledmap#6]
Hi,
first great plugin!

I use the page method to use it in my template but now I want to use it multiple times on one page.
This brings up error that the Google Maps JS is included multiple times and if I take look on the sourcecode every html instance have the same ID. Is there a possibility to use it multiple times on one page?

Cheers

**Comment by bnomei** [comment]
Thanks for your suggestion. I will take a look.

**Comment by bnomei** [comment]
I tried giving `js vars` and `init function` as well as the `map container div` unique keys in a dev branch. multiple maps will render, but only one will be interactive. [it seems like there should be only one](https://stackoverflow.com/questions/4074520/how-to-display-multiple-google-maps-per-page-with-api-v3) `js init function` to fix this. But doing that would require major changes to my plugin. i will target this for a kirby 3 rewrite.

i will upload the dev branch to master later today.

**Comment by janstieler** [comment]
Hi,
thanks for your efforts.
Maybe my interim solution could help someone, I changed my layout to one map and for the other maps i set a link and wrote the [lng], [lat] and [address] from @Fanningerts map Plugin in data-attributes
```
<?php
foreach($page->neighbourhoodinfos()->toStructure() as $neighbourhoodinfos):
    if($neighbourhoodinfos->location()->isNotEmpty()):
        $location = $neighbourhoodinfos->location()->yaml();
        $locationLat = $location['lat'];
        $locationZoom = $location['zoom'];
        $locationTitle = $location['address'];
?>
<a class="markerlink" href="#styledmap" data-lat="<?php echo $locationLat; ?>" data-lng="<?php echo $locationLng; ?>" data-zoom="<?php echo $locationZoom; ?>" data-title="<?php echo $locationTitle; ?>"><?php echo $locationTitle ?></a>
<?php
    endif;
endforeach;
?>
```
and in the js i wrote this data-attributes in variables and send it to the map:
````
$(document).on('click', '.marker-link', function(){
        var locationLat = $(this).data('lat');
        var locationLng = $(this).data('lng');
        var locationZoom = $(this).data('zoom');
        var locationTitle = $(this).data('title');

        var myLatlng = new google.maps.LatLng(locationLat,locationLng);
        var mapOptions = {
          zoom:locationZoom,
          center: myLatlng
        }
        var map = new google.maps.Map(document.getElementById("styledmap"), mapOptions);

        var marker = new google.maps.Marker({
            position: myLatlng,
            title:locationTitle
        });

        // To add the marker to the map, call setMap();
        marker.setMap(map);
    });
```

Cheers
