### ISSUE TITLE
Disable click on marker

### ISSUE THREAD

**Issue by janstieler** [bnomei/kirby-styledmap#7]
Hi,
how can I disable the clickevent on the marker?
I tried to set it in `plugin.styledmap.jsoptions` `clickable`to `false` but this doesn't work.

**Comment by bnomei** [comment]
try `c::set('plugin.styledmap.jsmarker.infoOpen', false);` or do not provide a url. you can check out the logic generating the click event here.

https://github.com/bnomei/kirby-styledmap/blob/master/snippets/styledmap-marker.php

if it does not solve it you could write your own snippet and reference it in the settings here
https://github.com/bnomei/kirby-styledmap#pluginstyledmapjsmarker

**Comment by janstieler** [comment]
Thanks bnomei,
but I have disabled your plugin and wrote complete my own maps script with the locationdata from @AugustMiller plugin. It was faster than struggle on every thing to find out how i can do it with your plugin.
Next time it will get a new change :).
